New & Exciting Error Messages
I wondered if this example code failed because it required `lodash`,
and at the time I was testing it neither `lodash` nor `bluebird`
was installed for promise handling.

Now that they are both installed and required at the top of the file,
we have new and exciting error messages:

```
error: [BOTPRESS] Unhandled error in middleware (outgoing). Error: An error has been returned by Facebook API.
Status: 400 (Bad Request)
(#100) name_placeholder[elements][0][image_url] should represent a valid URL
13:21:55 - error: Unhandled Rejection in Promise:  Promise {
  _bitField: 18087936,
  _fulfillmentHandler0:
   Error: An error has been returned by Facebook API.
   Status: 400 (Bad Request)
   (#100) name_placeholder[elements][0][image_url] should represent a valid URL
       at /Users/lisawilliams/wdi/projects/trollbustersbot/node_modules/botpress-messenger/bin/webpack:/src/messenger.js:600:13

```

Next steps: add image files at the appropriate relative locations indicated
in `static_data.js` and see if it works.

Responds to Issue #1. Going to switch back to `master` and restart
the heroku dynos -- this test was carried out on `localhost` using
`ngrok`. To do next test, run `heroku stop [name of dyno]` and then
restart the botpress server (shut down using `Ctrl+C` and restart
using `bp start`).